### ISSUE TITLE
parser_f() got an unexpected keyword argument 'on_bad_lines'

### ISSUE THREAD

**Issue by darkzbaron** [adam1brownell/garmin_data#1]
Hi there, thanks for the script, it really saves a bunch of times. Any idea why I am getting this error running Python36 and Pandas Version: 0.25.3

**Comment by adam1brownell** [comment]
`on_bad_lines` is a parameter for the `pd.read_csv` function. It was introduced in pandas `1.3.0`, so updating your pandas version should solve this issue.

**Comment by darkzbaron** [comment]
Also, out of curiosity because we probably go the same way, what sort of time series analysis did you perform, which machine learning models was most suitable for that type of data? Many thanks again for your code!
